name: Supabase Migrations

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Supabase CLI
        run: npm i -g supabase@latest

      - name: Supabase db push (remote)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          if [ -z "$SUPABASE_DB_URL" ]; then
            echo "SUPABASE_DB_URL is not set. Skipping remote push." && exit 0
          fi
          supabase db push --db-url "$SUPABASE_DB_URL"

      - name: Seed dev data (optional)
        if: ${{ secrets.SEED_DEV == 'true' }}
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          if [ -z "$SUPABASE_DB_URL" ]; then
            echo "SUPABASE_DB_URL is not set. Skipping seed." && exit 0
          fi
          supabase db execute --file supabase/seed.sql --db-url "$SUPABASE_DB_URL"


