name: Supabase Migrations

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabase db push (remote)
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          if [ -z "$SUPABASE_DB_URL" ]; then
            echo "SUPABASE_DB_URL is not set. Skipping remote push." && exit 0
          fi
          supabase db push --db-url "$SUPABASE_DB_URL"

      - name: Seed dev data (optional)
        if: ${{ secrets.SEED_DEV == 'true' }}
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          if [ -z "$SUPABASE_DB_URL" ]; then
            echo "SUPABASE_DB_URL is not set. Skipping seed." && exit 0
          fi
          supabase db execute --file supabase/seed.sql --db-url "$SUPABASE_DB_URL"


