name: Supabase Migrations

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Run migrations with psql (remote)
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          set -euo pipefail
          if [ -z "${SUPABASE_DB_URL:-}" ]; then
            echo "SUPABASE_DB_URL is not set. Skipping remote push." && exit 0
          fi
          for f in $(ls -1 supabase/migrations/*.sql | sort); do
            echo "Applying migration: $f"
            psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f "$f"
          done

      - name: Seed dev data (optional)
        if: ${{ secrets.SEED_DEV == 'true' }}
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          if [ -z "${SUPABASE_DB_URL:-}" ]; then
            echo "SUPABASE_DB_URL is not set. Skipping seed." && exit 0
          fi
          psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f supabase/seed.sql


